ResumeApp/ResumeApp/Models/ErrorViewModel.cs
using System;

namespace ResumeApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ResumeApp/ResumeApp/Models/Information.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ResumeApp.Models
{
    public class Information
    {
        [Key] public int ID { get; set; }
        public string FullName { get; set;}
        public string Email { get; set;}
        public string Birthday { get; set;}
        public int PhoneNumber { get; set;}
        public string AboutMe { get; set;}
        public string Experience { get; set;}
        public string Skills { get; set;}
        public string Hobbies { get; set;}


        public Information()
        {

        }
    }
}

ResumeApp/ResumeApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ResumeApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ResumeApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ResumeApp/ResumeApp/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ResumeApp.Data;
using ResumeApp.Models;

namespace ResumeApp.Controllers
{
    public class InformationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InformationController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Information
        public async Task<IActionResult> Index()
        {
            return View(await _context.Information.ToListAsync());
        }

       
        // GET: Information/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var information = await _context.Information
                .FirstOrDefaultAsync(m => m.ID == id);
            if (information == null)
            {
                return NotFound();
            }

            return View(information);
        }

        // GET: Information/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Information/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FullName,Email,Birthday,PhoneNumber,AboutMe,Experience,Skills,Hobbies")] Information information)
        {
            if (ModelState.IsValid)
            {
                _context.Add(information);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(information);
        }

        // GET: Information/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var information = await _context.Information.FindAsync(id);
            if (information == null)
            {
                return NotFound();
            }
            return View(information);
        }

        // POST: Information/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FullName,Email,Birthday,PhoneNumber,AboutMe,Experience,Skills,Hobbies")] Information information)
        {
            if (id != information.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(information);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InformationExists(information.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(information);
        }

        // GET: Information/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var information = await _context.Information
                .FirstOrDefaultAsync(m => m.ID == id);
            if (information == null)
            {
                return NotFound();
            }

            return View(information);
        }

        // POST: Information/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var information = await _context.Information.FindAsync(id);
            _context.Information.Remove(information);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InformationExists(int id)
        {
            return _context.Information.Any(e => e.ID == id);
        }
    }
}

ResumeApp/ResumeApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Resume App</h1>
    <p>Please proceed under the information tab to create your resume, or view a resume of another user.</a>.</p>
</div>

ResumeApp/ResumeApp/Views/Information/Create.cshtml
@model ResumeApp.Models.Information

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Information</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AboutMe" class="control-label"></label>
                <input asp-for="AboutMe" class="form-control" />
                <span asp-validation-for="AboutMe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skills" class="control-label"></label>
                <input asp-for="Skills" class="form-control" />
                <span asp-validation-for="Skills" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hobbies" class="control-label"></label>
                <input asp-for="Hobbies" class="form-control" />
                <span asp-validation-for="Hobbies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ResumeApp/ResumeApp/Views/Information/Delete.cshtml
@model ResumeApp.Models.Information

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Information</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AboutMe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AboutMe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Experience)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Experience)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Skills)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Skills)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hobbies)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hobbies)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ResumeApp/ResumeApp/Views/Information/Details.cshtml
@model ResumeApp.Models.Information

@{
    ViewData["Title"] = "Details";
}



<h1> <b> @Html.DisplayFor(model => model.FullName)'s </b> Resume</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FullName) </br>
            <b> @Html.DisplayFor(model => model.FullName) </b>
        </dt>
        <dd class="col-sm-10">
            <b> @Html.DisplayNameFor(model => model.AboutMe) </b> </br>
            @Html.DisplayFor(model => model.AboutMe)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email) </br>
            @Html.DisplayFor(model => model.Email) </br>
          </br>  @Html.DisplayNameFor(model => model.Birthday) </br>
            @Html.DisplayFor(model => model.Birthday) </br>
           </br> @Html.DisplayNameFor(model => model.PhoneNumber) </br>
            (+383)@Html.DisplayFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            <b> @Html.DisplayNameFor(model => model.Experience) </b> </br>
               @Html.DisplayFor(model => model.Experience)
        </dd>
        <dt class="col-sm-2">
        
        </dt>
        <dd class="col-sm-10">
          <b>  @Html.DisplayNameFor(model => model.Skills) </b></br>
            @Html.DisplayFor(model => model.Skills)
        </dd>
        <dt class="col-sm-2">
        
        </dt>
        <dd class="col-sm-10">
            <b> @Html.DisplayNameFor(model => model.Hobbies) </b> </br>
            @Html.DisplayFor(model => model.Hobbies)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

ResumeApp/ResumeApp/Views/Information/Edit.cshtml
@model ResumeApp.Models.Information

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Information</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AboutMe" class="control-label"></label>
                <input asp-for="AboutMe" class="form-control" />
                <span asp-validation-for="AboutMe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skills" class="control-label"></label>
                <input asp-for="Skills" class="form-control" />
                <span asp-validation-for="Skills" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hobbies" class="control-label"></label>
                <input asp-for="Hobbies" class="form-control" />
                <span asp-validation-for="Hobbies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ResumeApp/ResumeApp/Views/Information/Index.cshtml
@model IEnumerable<ResumeApp.Models.Information>

@{
    ViewData["Title"] = "Index";
}

<h1>Create or view a Resume</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
              (+383)@Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.ID">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

ResumeApp/ResumeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ResumeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ResumeApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Information" asp-action="Index">Information</a>
                        </li>
                
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ResumeApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>